language: generic
sudo: true
dist: trusty
env:
  global:
  - DEB_BUILD_OPTIONS='parallel=5'
  - VERSION=2.0.3
  - REVISION=0
install:
- sudo apt-get update
- sudo apt-get install -yq software-properties-common
- sudo add-apt-repository "deb http://us-central1.gce.clouds.archive.ubuntu.com/ubuntu
  $(lsb_release -sc) main universe restricted multiverse"
- sudo add-apt-repository -y ppa:radio-astro/main
- sudo apt-get update
- sudo apt-get install -yq devscripts debhelper build-essential cmake flex bison libblas-dev
  liblapack-dev libcfitsio3-dev wcslib-dev libfftw3-dev gfortran libncurses5-dev libreadline6-dev
  casacore-data libhdf5-dev
script:
- curl -L -o casacore_$VERSION.orig.tar.gz https://github.com/casacore/casacore/archive/v$VERSION.tar.gz
- tar zxvpf casacore_$VERSION.orig.tar.gz
- cd casacore-$VERSION
- cp -av ../debian .
- dch -v ${VERSION}-${REVISION} -D stable "auto build"
- dpkg-buildpackage -us -uc
- cd ..
before_deploy:
- ls *.deb
deploy:
  provider: bintray
  file: descriptor.json
  skip_cleanup: true
  user: gijzelaerr
  key:
    secure: ketQWlyfbUqcdnDi0fC4DZz5zTL7t7IwR3oRD3/wdeMLUCYsDbgT4I/U/XLNN8buXJrCpF/sVh/u0JtdHigdlcxu1LoleI/beqYwCZRvE2GCNhVS5lopN4Bn+inVF7Pw3rSWdCrxw0T9y60d9i2RzPRaF1jOViFW7RVrLwrPN9E=
  on: bintray
